### ISSUE TITLE
LegendaryBlockchain

### ISSUE THREAD

**Issue by hotnotHD** [SemenMartynov/Software-Engineering-2022#280]
Student, group: Ковалевский Денис, 3530901/90201
URL: https://github.com/hotnotHD/LegendaryBlockchain 
Any comments: git-flow, Python, Flask

**Comment by SemenMartynov** [comment]
Хм... кажется что-то пошло не так:
```
node2  | ----------------------------------------
node3  | ----------------------------------------
node2  | Exception occurred during processing of request from ('127.0.0.1', 34334)
node3  | Exception occurred during processing of request from ('127.0.0.1', 59360)
node1  | ----------------------------------------
node1  | Exception occurred during processing of request from ('127.0.0.1', 50200)
node1  | ----------------------------------------
node1  | Exception occurred during processing of request from ('127.0.0.1', 50208)
node2  | ----------------------------------------
node2  | Exception occurred during processing of request from ('127.0.0.1', 34336)
node3  | ----------------------------------------
node3  | Exception occurred during processing of request from ('127.0.0.1', 59370)
node1  | ----------------------------------------
node1  | Exception occurred during processing of request from ('127.0.0.1', 50222)
node2  | ----------------------------------------
node3  | ----------------------------------------
node2  | Exception occurred during processing of request from ('127.0.0.1', 34346)
node3  | Exception occurred during processing of request from ('127.0.0.1', 59372)
node2  | Traceback (most recent call last):
node2  |   File "/usr/local/lib/python3.11/socketserver.py", line 691, in process_request_thread
node2  |     self.finish_request(request, client_address)
node3  | Traceback (most recent call last):
node2  |   File "/usr/local/lib/python3.11/socketserver.py", line 361, in finish_request
node2  |     self.RequestHandlerClass(request, client_address, self)
node2  |   File "/usr/local/lib/python3.11/socketserver.py", line 755, in __init__
node2  |     self.handle()
node3  |   File "/usr/local/lib/python3.11/socketserver.py", line 691, in process_request_thread
node3  |     self.finish_request(request, client_address)
node3  |   File "/usr/local/lib/python3.11/socketserver.py", line 361, in finish_request
node3  |     self.RequestHandlerClass(request, client_address, self)
node3  |   File "/usr/local/lib/python3.11/socketserver.py", line 755, in __init__
node3  |     self.handle()
node2  |   File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 361, in handle
node2  |     super().handle()
node2  |   File "/usr/local/lib/python3.11/http/server.py", line 432, in handle
node2  |     self.handle_one_request()
node3  |   File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 361, in handle
node3  |     super().handle()
node2  |   File "/usr/local/lib/python3.11/http/server.py", line 400, in handle_one_request
node2  |     self.raw_requestline = self.rfile.readline(65537)
node2  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
node2  |   File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
node2  |     return self._sock.recv_into(b)
node2  |            ^^^^^^^^^^^^^^^^^^^^^^^
node2  |   File "/usr/local/lib/python3.11/site-packages/gevent/_socketcommon.py", line 693, in recv_into
node2  |     self._wait(self._read_event)
node2  |   File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
node2  |   File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
node2  |   File "src/gevent/_hub_primitives.py", line 304, in gevent._gevent_c_hub_primitives._primitive_wait
node2  |   File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
node2  |   File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
node2  |   File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
node2  |   File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
node2  |   File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
node2  |   File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
node2  |   File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
node2  |   File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
node2  | greenlet.error: cannot switch to a different thread
node2  | ----------------------------------------
node2  | Traceback (most recent call last):
node2  |   File "/usr/local/lib/python3.11/socketserver.py", line 691, in process_request_thread
node2  |     self.finish_request(request, client_address)
node2  |   File "/usr/local/lib/python3.11/socketserver.py", line 361, in finish_request
node2  |     self.RequestHandlerClass(request, client_address, self)
node2  |   File "/usr/local/lib/python3.11/socketserver.py", line 755, in __init__
node2  |     self.handle()
node2  |   File "/usr/local/lib/python3.11/site-packages/werkzeug/serving.py", line 361, in handle
node2  |     super().handle()
node2  |   File "/usr/local/lib/python3.11/http/server.py", line 432, in handle
node2  |     self.handle_one_request()
node2  |   File "/usr/local/lib/python3.11/http/server.py", line 400, in handle_one_request
node2  |     self.raw_requestline = self.rfile.readline(65537)
node2  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
node2  | Traceback (most recent call last):
```

Потом я вижу
```
node4 exited with code 0
```
И вроде всё, никакой больше активности...

**Comment by hotnotHD** [comment]
Если в конце 
`node4 exited with code 0`
А перед этим выведены цепочки с трех нод, к примеру:
`node4  | NODE 3:
node4  |
node4  | [{'index': '0', 'prev_hash': 'GENESIS', 'hash': '688d1e24d5ef2de65f5424714703be2702ef9ea715d26a19e4880497b4610000', 'data': 'inbbrpptalybpuiwygrikwhnaeswijndsjddjbbdlznvrjtrscjrhltlnocbtsosclfeshbzuyekkbwocudguikkolkpfwkwzpkywvsqftprrequjlhvcgsjeazbncpglupyzlqklljcloxpziobzrxyqfungkmbnyrbwubjefvnnqvjrikxmkndguweuyfwdlsfoxmydtqfmruccnxzjgnlvduykhtqvadiavdnicqxesgklfspxjscbqpslrrk', 'nonce': '851555', 'time': '1681644186.673104'}, {'index': '1', 'prev_hash': '688...`
То все правильно работает
Ошибки в начале это из-за дудоса запросами, их выводит фласк

**Comment by hotnotHD** [comment]
@SemenMartynov

**Comment by SemenMartynov** [comment]
А, понял, ок.
