### ISSUE TITLE
Basic Blockchain

### ISSUE THREAD

**Issue by OGSegu** [SemenMartynov/Software-Engineering-2022#283]
Student, group: Кривицкий В.В. 90202
URL: https://github.com/OGSegu/BasicBlockChain
Any comments: Java, gRPC

**Comment by SemenMartynov** [comment]
Будут резолвиться те имена, которые заданы в компоузе.

Без этого -- пачка варнинов.
```
node_0  | Block broadcast returned: [org.main.grpc.entity.MinedBlockResponse@2046b658[host=host.docker.internal:9021,minedBlockResponseCode=FAILED,block=<null>];org.main.grpc.entity.MinedBlockResponse@172a881a[host=host.docker.internal:9022,minedBlockResponseCode=FAILED,block=<null>]]
node_0  | Apr 16, 2023 12:17:58 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
node_0  | WARNING: [Channel<1>: (host.docker.internal:9021)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host host.docker.internal, cause=java.lang.RuntimeException: java.net.UnknownHostException: host.docker.internal
node_0  | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
node_0  | 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
node_0  | 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
node_0  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
node_0  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
node_0  | 	at java.base/java.lang.Thread.run(Thread.java:833)
node_0  | Caused by: java.net.UnknownHostException: host.docker.internal
node_0  | 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
node_0  | 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
node_0  | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
node_0  | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
node_0  | 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
node_0  | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
node_0  | 	... 5 more
node_0  | }
node_1  | Apr 16, 2023 12:18:00 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
node_1  | WARNING: [Channel<1>: (host.docker.internal:9020)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host host.docker.internal, cause=java.lang.RuntimeException: java.net.UnknownHostException: host.docker.internal
node_1  | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
node_1  | 	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
node_1  | 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
node_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
node_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
node_1  | 	at java.base/java.lang.Thread.run(Thread.java:833)
node_1  | Caused by: java.net.UnknownHostException: host.docker.internal
node_1  | 	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
node_1  | 	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
node_1  | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
node_1  | 	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
node_1  | 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
node_1  | 	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
node_1  | 	... 5 more
node_1  | }
```
