### ISSUE TITLE
🤡ClownChain🤡

### ISSUE THREAD

**Issue by semwai** [SemenMartynov/Software-Engineering-2022#316]
Student, group: Шахбазов Эльвин 3530901/90201
URL: https://github.com/semwai/clownchain
Any comments: python, pytest, fastapi

**Comment by SemenMartynov** [comment]
```
------                                                                                                                                                                                                                                        
 > [builder 6/6] RUN pipenv requirements > requirements.txt:                                                                                                                                                                                  
#0 0.676 Traceback (most recent call last):                                                                                                                                                                                                   
#0 0.676   File "/usr/local/bin/pipenv", line 8, in <module>                                                                                                                                                                             0.0s
#0 0.676     sys.exit(cli())ntext                                                                                                                                                                                                        0.1s
#0 0.676   File "/usr/local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__                                                                                                                            0.0s
#0 0.676     return self.main(*args, **kwargs)
#0 0.676   File "/usr/local/lib/python3.10/site-packages/pipenv/cli/options.py", line 58, in main
#0 0.676     return super().main(*args, **kwargs, windows_expand_args=False)
#0 0.676   File "/usr/local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1055, in main
#0 0.677     rv = self.invoke(ctx)
#0 0.677   File "/usr/local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
#0 0.677     return _process_result(sub_ctx.command.invoke(sub_ctx))
#0 0.677   File "/usr/local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
#0 0.677     return ctx.invoke(self.callback, **ctx.params)
#0 0.677   File "/usr/local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
#0 0.677     return __callback(*args, **kwargs)
#0 0.677   File "/usr/local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
#0 0.677     return ctx.invoke(f, obj, *args, **kwargs)
#0 0.677   File "/usr/local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
#0 0.677     return __callback(*args, **kwargs)
#0 0.677   File "/usr/local/lib/python3.10/site-packages/pipenv/cli/command.py", line 781, in requirements
#0 0.677     lockfile = state.project.load_lockfile(expand_env_vars=False)
#0 0.677   File "/usr/local/lib/python3.10/site-packages/pipenv/project.py", line 1031, in load_lockfile
#0 0.678     with io.open(self.lockfile_location, encoding="utf-8") as lock:
#0 0.678 FileNotFoundError: [Errno 2] No such file or directory: '/app/Pipfile.lock'
------
failed to solve: process "/bin/sh -c pipenv requirements > requirements.txt" did not complete successfully: exit code: 1
```
![image](https://user-images.githubusercontent.com/1230054/233803945-4da2d21a-046d-4d08-b915-a7ed9be3da61.png)

**Comment by semwai** [comment]
я в .dockerignore засунул lock файл с зависимостями, это было ошибкой
![изображение](https://user-images.githubusercontent.com/33517045/233804014-48f77f85-c0ca-4edf-97f7-414720c377f5.png)

**Comment by semwai** [comment]
и пожалйлста не кидайте стрнншых клоунв
![изображение](https://user-images.githubusercontent.com/33517045/233804307-2f0cbe1c-3901-4adf-aa70-f1dadea16b8b.png)

**Comment by SemenMartynov** [comment]
![image](https://user-images.githubusercontent.com/1230054/233857452-30d96609-9987-4172-90d6-d483dd0de6ae.png)
