### ISSUE TITLE
PolyChain

### ISSUE THREAD

**Issue by ivanems** [SemenMartynov/Software-Engineering-2022#326]
Student, group: Морозов Иван, 3530901/90202
URL: https://github.com/ivannmm/PolyChain
Any comments: git-flow, Java

**Comment by SemenMartynov** [comment]
Третья нода упала, остальные непонятно что делают
```
$ docker compose --verbose up
[+] Building 0.0s (0/0)                                                                                                                                                                       
[+] Running 4/4
 ✔ Network polychain_default  Created                                                                                                                                                    0.0s 
 ✔ Container node2            Created                                                                                                                                                    0.1s 
 ✔ Container node1            Created                                                                                                                                                    0.1s 
 ✔ Container node3            Created                                                                                                                                                    0.1s 
Attaching to node1, node2, node3
node2  | May 17, 2023 9:46:02 PM sun.net.httpserver.ExchangeImpl sendResponseHeaders
node2  | WARNING: sendResponseHeaders: rCode = 204: forcing contentLen = -1
node1  | NO CONTENT
node3  | Exception in thread "main" java.lang.NullPointerException
node3  | 	at org.example.polychain.PolyBlock.calculateHash(PolyBlock.java:65)
node3  | 	at org.example.polychain.PolyBlock.<init>(PolyBlock.java:55)
node3  | 	at org.example.polychain.PolyChain.generateGenesisBlock(PolyChain.java:137)
node3  | 	at org.example.polychain.PolyChain.<init>(PolyChain.java:40)
node3  | 	at org.example.Main.startNode(Main.java:20)
node3  | 	at org.example.Main.main(Main.java:16)
node3 exited with code 1
```

Ещё непонятно зачем разносить на разные порты, если у нас уже есть разные ИПы.

В `readme.md` мы собираем `fierusoul/polychain_test`, а в комоузе запускаем `polychain_test`.

Список issues пуст, коммиты ни с чем не слинкованы.

**Comment by ivanems** [comment]
@SemenMartynov fixed.

**Comment by SemenMartynov** [comment]
У тебя есть доменные имена соседей, на надо хардокодить ИПы -- `RECEIVERS: http://172.17.0.1:8082,http://172.17.0.1:8083`
